

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShopApplicationByFizo.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class opennosEntities2 : DbContext
{
    public opennosEntities2()
        : base("name=opennosEntities2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Account> Account { get; set; }

    public virtual DbSet<Character> Character { get; set; }

}

}

