// <auto-generated />
namespace OpenNos.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-beta1-61024")]
    public sealed partial class Aphrodite69 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aphrodite69));
        
        string IMigrationMetadata.Id
        {
            get { return "201710251653572_Aphrodite69"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
