//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.Master.Server.Resource {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenNos.Master.Server.Resource.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta ya está conectada..
        /// </summary>
        internal static string ALREADY_CONNECTED {
            get {
                return ResourceManager.GetString("ALREADY_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted ha sido prohibido. Motivo {0}, hasta {1}.
        /// </summary>
        internal static string BANNED {
            get {
                return ResourceManager.GetString("BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexión cerrada por el cliente..
        /// </summary>
        internal static string CLIENT_CLOSED {
            get {
                return ResourceManager.GetString("CLIENT_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexión cerrada..
        /// </summary>
        internal static string CLIENT_DISCONNECTED {
            get {
                return ResourceManager.GetString("CLIENT_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Config cargada!.
        /// </summary>
        internal static string CONFIG_LOADED {
            get {
                return ResourceManager.GetString("CONFIG_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONNECT {0} Conectado - SessionId: {1}.
        /// </summary>
        internal static string CONNECTION {
            get {
                return ResourceManager.GetString("CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexión cerrada..
        /// </summary>
        internal static string CONNECTION_CLOSED {
            get {
                return ResourceManager.GetString("CONNECTION_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La conexión al servidor se ha perdido..
        /// </summary>
        internal static string CONNECTION_LOST {
            get {
                return ResourceManager.GetString("CONNECTION_LOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Packet with Header {0} está dañado o PacketDefinition no es válido. Contenido: {1}.
        /// </summary>
        internal static string CORRUPT_PACKET {
            get {
                return ResourceManager.GetString("CORRUPT_PACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡La base de datos ha sido inicializada!.
        /// </summary>
        internal static string DATABASE_INITIALIZED {
            get {
                return ResourceManager.GetString("DATABASE_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La base de datos puede no estar actualizada. Por favor considere actualizar su base de datos..
        /// </summary>
        internal static string DATABASE_NOT_UPTODATE {
            get {
                return ResourceManager.GetString("DATABASE_NOT_UPTODATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente desconectado! ClientId =.
        /// </summary>
        internal static string DISCONNECT {
            get {
                return ResourceManager.GetString("DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconexión forzada del cliente {0}, demasiadas conexiones..
        /// </summary>
        internal static string FORCED_DISCONNECT {
            get {
                return ResourceManager.GetString("FORCED_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ID o Contraseña equivocada!.
        /// </summary>
        internal static string IDERROR {
            get {
                return ResourceManager.GetString("IDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor se encuentra actualmente en mantenimiento. Tiempo estimado de mantenimiento {0}.
        /// </summary>
        internal static string MAINTENANCE {
            get {
                return ResourceManager.GetString("MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje recibido {0} en el cliente {1}.
        /// </summary>
        internal static string MESSAGE_RECEIVED {
            get {
                return ResourceManager.GetString("MESSAGE_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje enviado al cliente.
        /// </summary>
        internal static string MSG_SENT {
            get {
                return ResourceManager.GetString("MSG_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo cliente conectado. ClientId =.
        /// </summary>
        internal static string NEW_CONNECT {
            get {
                return ResourceManager.GetString("NEW_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta no validada.
        /// </summary>
        internal static string NOTVALIDATE {
            get {
                return ResourceManager.GetString("NOTVALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar el paquete {0} al cliente {1}, {2}..
        /// </summary>
        internal static string PACKET_FAILURE {
            get {
                return ResourceManager.GetString("PACKET_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MasterServer se inició correctamente..
        /// </summary>
        internal static string STARTED {
            get {
                return ResourceManager.GetString("STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mensaje es demasiado grande ({0} bytes). La longitud máxima permitida es {1} bytes..
        /// </summary>
        internal static string TOO_BIG {
            get {
                return ResourceManager.GetString("TOO_BIG", resourceCulture);
            }
        }
    }
}
