DELETE
FROM
    [opennos].[dbo].[Drop]
WHERE
    [ItemVNum] = '2115' -- légumes
OR [ItemVNum] = '2099' -- Fruits rouge
OR [ItemVNum] = '2118' -- Fruits de mer
OR [ItemVNum] = '2179' -- Masse gluante bleue
OR [ItemVNum] = '2180' -- Masse gluante verte
OR [ItemVNum] = '2177' -- Masse gluante rouge
OR [ItemVNum] = '2205' -- Pierre mystérieuse
OR [ItemVNum] = '2101' -- Encre mystérieuse
OR [ItemVNum] = '2307' -- Glaçon
OR [ItemVNum] = '2308' -- Lait
OR [ItemVNum] = '1237' -- Combi bottes Type A
OR [ItemVNum] = '1238' -- Combi bottes Type B
OR [ItemVNum] = '1239' -- Combi gants Type A
OR [ItemVNum] = '1240' -- Combu gants Type B
OR [ItemVNum] = '1313' -- Parchemin d'arme A d'Amir
OR [ItemVNum] = '5119' -- Boosteur de vitesse
OR [ItemVNum] = '1241' -- Recette de consommables
OR [ItemVNum] = '2098' -- Herbe
OR [ItemVNum] = '2100' -- Herbe bleue
OR [ItemVNum] = '2264' -- Lambeau de peau
OR [ItemVNum] = '2277' -- Sang coagulé
OR [ItemVNum] = '2117' -- Viande
OR [ItemVNum] = '2276' -- Dent de sangsue
OR [ItemVNum] = '2208' -- Bobine
OR [ItemVNum] = '2278' -- Gel vert
OR [ItemVNum] = '2129' -- Entraineur de nosmates fort
OR [ItemVNum] = '2102' -- Betterave
OR [ItemVNum] = '2207' -- Plume d'or
OR [ItemVNum] = '2114' -- Céréales
OR [ItemVNum] = '2142' -- Musli
OR [ItemVNum] = '2206' -- Pomme
OR [ItemVNum] = '2379' -- Viande d'agneau
OR [ItemVNum] = '2353' -- Tissu chaud
OR [ItemVNum] = '2352' -- Cuir chaud
OR [ItemVNum] = '2354' -- Bois chaud
OR [ItemVNum] = '2355' -- Fil d'argent chaud
OR [ItemVNum] = '2356' -- Fil d'or chaud
OR [ItemVNum] = '2458' -- Baguette de sourcier antique
OR [ItemVNum] = '2810' -- Queue de Bacoum
OR [ItemVNum] = '2296' -- Eau
OR [ItemVNum] = '2804' -- Essence de la balance
OR [ItemVNum] = '2818' -- Collier en argent
OR [ItemVNum] = '2806' -- Relique de la tribu originelle
OR [ItemVNum] = '2807' -- Relique de la tribu originelle intact
OR [ItemVNum] = '2805' -- Cristal de la balance
OR [ItemVNum] = '2803' -- Element de la balance
OR [ItemVNum] = '2819' -- Collier en or
OR [ItemVNum] = '2809' -- Corne de bacoum
OR [ItemVNum] = '2230' -- Vis géante
OR [ItemVNum] = '2225' -- Ecrou géant
OR [ItemVNum] = '2256' -- Brannche rouge
OR [ItemVNum] = '2243' -- Engrenage
OR [ItemVNum] = '2817' -- Sanctuaire inconnu
OR [ItemVNum] = '2260' -- Cristal des souhaits
OR [ItemVNum] = '1259' -- Poussiere de mites
OR [ItemVNum] = '2265' -- Poussiere de mites
OR [ItemVNum] = '2246' -- Queue de rat
OR [ItemVNum] = '2227' -- Fer à yak
OR [ItemVNum] = '2253' -- Ramure de yak
OR [ItemVNum] = '2271' -- Crinière brune
OR [ItemVNum] = '1312' -- Parchemin d'armure d'Amir
OR [ItemVNum] = '1313' -- Parchemin d'arme A d'Amir
OR [ItemVNum] = '1314' -- Parchemin d'arme B d'Amir
OR [ItemVNum] = '1315' -- Spécifications de l'arme d'Amir
OR [ItemVNum] = '1316' -- Couverture du livre de spécifications d'arme d'Amir
OR [ItemVNum] = '1235' -- Plan de construction lvl 1
OR [ItemVNum] = '1236' -- Plan de construction lvl 2
OR [ItemVNum] = '5879' -- Energie instable
OR [ItemVNum] = '1028' -- Cristal de nouvelle lune
OR [ItemVNum] = '1092' -- Pierre d'espace-temps
OR [ItemVNum] = '1093' -- Pierre d'espace-temps
OR [ItemVNum] = '1094' -- Morceau d'espace-temps raid
OR [ItemVNum] = '4095' -- none
OR [ItemVNum] = '1096' -- Pierre d'espace-temps labo
OR [ItemVNum] = '1317' -- Pierre d'espace-temps basilic
OR [ItemVNum] = '1318' -- Pierre d'espace-temps chevalier infernal
OR [ItemVNum] = '1319' -- Pierre d'espace-temps treekun
OR [ItemVNum] = '1320' -- Pierre d'espace-temps Chrysos
OR [ItemVNum] = '2232'; -- Molaire géante
