//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNos.Import.Console.Resource {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenNos.Import.Console.Resource.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos uno de los archivos necesarios falta.
        /// </summary>
        internal static string AT_LEAST_ONE_FILE_MISSING {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} tarjetas analizadas.
        /// </summary>
        internal static string CARDS_PARSED {
            get {
                return ResourceManager.GetString("CARDS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La base de datos ha sido inicializada..
        /// </summary>
        internal static string DATABASE_INITIALIZED {
            get {
                return ResourceManager.GetString("DATABASE_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La base de datos puede no estar actualizada. Por favor considere actualizar su base de datos..
        /// </summary>
        internal static string DATABASE_NOT_UPTODATE {
            get {
                return ResourceManager.GetString("DATABASE_NOT_UPTODATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Parsing hecho!.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} artículos de drop analizados.
        /// </summary>
        internal static string DROP_PARSED {
            get {
                return ResourceManager.GetString("DROP_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese el directorio de archivos para analizar.
        /// </summary>
        internal static string ENTER_PATH {
            get {
                return ResourceManager.GetString("ENTER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} elementos analizados.
        /// </summary>
        internal static string ITEMS_PARSED {
            get {
                return ResourceManager.GetString("ITEMS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} mapas analizados.
        /// </summary>
        internal static string MAPS_PARSED {
            get {
                return ResourceManager.GetString("MAPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MapTypeMaps analizados.
        /// </summary>
        internal static string MAPTYPEMAPS_PARSED {
            get {
                return ResourceManager.GetString("MAPTYPEMAPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MapTypes analizados.
        /// </summary>
        internal static string MAPTYPES_PARSED {
            get {
                return ResourceManager.GetString("MAPTYPES_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} monstruos analizados.
        /// </summary>
        internal static string MONSTERS_PARSED {
            get {
                return ResourceManager.GetString("MONSTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas un árbol de directorios como este:.
        /// </summary>
        internal static string NEED_TREE {
            get {
                return ResourceManager.GetString("NEED_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Esta identificación de artículo no es válida!.
        /// </summary>
        internal static string NO_ITEM {
            get {
                return ResourceManager.GetString("NO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} npc-monsters analizados.
        /// </summary>
        internal static string NPCMONSTERS_PARSED {
            get {
                return ResourceManager.GetString("NPCMONSTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} npcs analizado.
        /// </summary>
        internal static string NPCS_PARSED {
            get {
                return ResourceManager.GetString("NPCS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar las cuentas?.
        /// </summary>
        internal static string PARSE_ACCOUNTS {
            get {
                return ResourceManager.GetString("PARSE_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar TODO?.
        /// </summary>
        internal static string PARSE_ALL {
            get {
                return ResourceManager.GetString("PARSE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar tarjetas?.
        /// </summary>
        internal static string PARSE_CARDS {
            get {
                return ResourceManager.GetString("PARSE_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar Drop? para el uso de drop dependiente de MapType MapTypes!.
        /// </summary>
        internal static string PARSE_DROP {
            get {
                return ResourceManager.GetString("PARSE_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar elementos?.
        /// </summary>
        internal static string PARSE_ITEMS {
            get {
                return ResourceManager.GetString("PARSE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar MapNpcs?.
        /// </summary>
        internal static string PARSE_MAPNPCS {
            get {
                return ResourceManager.GetString("PARSE_MAPNPCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar Mapas?.
        /// </summary>
        internal static string PARSE_MAPS {
            get {
                return ResourceManager.GetString("PARSE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar MapTypes? sugerimos usar con MapTypeMaps.
        /// </summary>
        internal static string PARSE_MAPTYPES {
            get {
                return ResourceManager.GetString("PARSE_MAPTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar NpcMonsters?.
        /// </summary>
        internal static string PARSE_MONSTERS {
            get {
                return ResourceManager.GetString("PARSE_MONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar NpcMonsterData?.
        /// </summary>
        internal static string PARSE_NPCMONSTERDATA {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar Npcs?.
        /// </summary>
        internal static string PARSE_NPCMONSTERS {
            get {
                return ResourceManager.GetString("PARSE_NPCMONSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar Portals?.
        /// </summary>
        internal static string PARSE_PORTALS {
            get {
                return ResourceManager.GetString("PARSE_PORTALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar Recetas?.
        /// </summary>
        internal static string PARSE_RECIPES {
            get {
                return ResourceManager.GetString("PARSE_RECIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar Shopitems?.
        /// </summary>
        internal static string PARSE_SHOPITEMS {
            get {
                return ResourceManager.GetString("PARSE_SHOPITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar Tiendas?.
        /// </summary>
        internal static string PARSE_SHOPS {
            get {
                return ResourceManager.GetString("PARSE_SHOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar Shopkills.
        /// </summary>
        internal static string PARSE_SHOPSKILLS {
            get {
                return ResourceManager.GetString("PARSE_SHOPSKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar Habilidades?.
        /// </summary>
        internal static string PARSE_SKILLS {
            get {
                return ResourceManager.GetString("PARSE_SKILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres analizar Teleporters?.
        /// </summary>
        internal static string PARSE_TELEPORTERS {
            get {
                return ResourceManager.GetString("PARSE_TELEPORTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} portales analizados.
        /// </summary>
        internal static string PORTALS_PARSED {
            get {
                return ResourceManager.GetString("PORTALS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} recetas analizadas.
        /// </summary>
        internal static string RECIPES_PARSED {
            get {
                return ResourceManager.GetString("RECIPES_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RespawnTypes analizados.
        /// </summary>
        internal static string RESPAWNTYPE_PARSED {
            get {
                return ResourceManager.GetString("RESPAWNTYPE_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} shopitems analizados.
        /// </summary>
        internal static string SHOPITEMS_PARSED {
            get {
                return ResourceManager.GetString("SHOPITEMS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} tiendas analizadas.
        /// </summary>
        internal static string SHOPS_PARSED {
            get {
                return ResourceManager.GetString("SHOPS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} shopskills analizadas.
        /// </summary>
        internal static string SHOPSKILLS_PARSED {
            get {
                return ResourceManager.GetString("SHOPSKILLS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} habilidades analizadas.
        /// </summary>
        internal static string SKILLS_PARSED {
            get {
                return ResourceManager.GetString("SKILLS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} teletransportadores analizados.
        /// </summary>
        internal static string TELEPORTERS_PARSED {
            get {
                return ResourceManager.GetString("TELEPORTERS_PARSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} espacios de tiempo analizados.
        /// </summary>
        internal static string TIMESPACES_PARSED {
            get {
                return ResourceManager.GetString("TIMESPACES_PARSED", resourceCulture);
            }
        }
    }
}
