////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$HelpMe", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class HelpMePacket : PacketDefinition
    {
        #region Methods

        public static string ReturnHelp()
        {
            return "$HelpMe";
        }

        #endregion
    }
}