//// <auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$ChangeSex", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class ChangeSexPacket : PacketDefinition
    {
        public static string ReturnHelp()
        {
            return "$ChangeSex"; // Love you should use this command to define a your own Real-life gender because you do not have one actually <3
        }
    }
}