////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Faction", PassNonParseablePacket = true, Authority = AuthorityType.Operator)]
    public class FactionPacket : PacketDefinition
    {
        public static string ReturnHelp()
        {
            return "$Faction";
        }
    }
}