////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Warp", PassNonParseablePacket = true, Authority = AuthorityType.User)]
    public class WarpPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Data { get; set; }

        public static string ReturnHelp()
        {
            return "$Warp <Place>";
        }

        #endregion
    }
}